#ifndef OVDBUTIL_INTERFACE_1604911737496_H
#define OVDBUTIL_INTERFACE_1604911737496_H
#include "ccglobal/export.h"

#if USE_OVDBUTIL_DLL
	#define OVDBUTIL_API CC_DECLARE_IMPORT
#elif USE_OVDBUTIL_STATIC
	#define OVDBUTIL_API CC_DECLARE_STATIC
#else
	#if OVDBUTIL_DLL
		#define OVDBUTIL_API CC_DECLARE_EXPORT
	#else
		#define OVDBUTIL_API CC_DECLARE_STATIC
	#endif
#endif
#endif // OVDBUTIL_INTERFACE_1604911737496_H